#!/bin/bash

MASTER="master"
MAIN="main"

git fetch


if [ "$(git rev-parse $MASTER)" = "$(git merge-base $MASTER $MAIN)" ]; then
  echo "$MAIN branch is ahead or even with $MASTER"
else
  echo "$MASTER branch is ahead of $MAIN"
fi
