name: Check Branch Positions

on:
  push:
    branches:
      - master
      - development
      - main

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run branch check script
        run: |
          chmod +x shell_deneme
          ./shell_deneme
          
      - name: Check if master is ahead of development
        run: |
          MASTER_COMMIT=$(git rev-parse master)
          MAIN_COMMIT=$(git rev-parse main)
          if [ "$(git rev-list --count $MASTER_COMMIT..$MAIN_COMMIT)" -gt 0 ]; then
            echo "main is ahead of master"
          else
            echo "master is ahead of main"
          fi
